### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by Maximaximum** [BasicPrimitives/angular#4]
Hello!

Would you mind making a release that would support Angular 16?

**Comment by BasicPrimitives** [comment]
We plan to rework library into web component standard https://developer.mozilla.org/en-US/docs/Web/API/Web_components
So basically we plan the opposite, we are going to eliminate React, Angular and generic JavaScript APIs and replace all of them with unified web component API.

**Comment by BasicPrimitives** [comment]
Updated up to ver 16
