### ISSUE TITLE
Angular v17 Support

### ISSUE THREAD

**Issue by swami-sanapathi** [BasicPrimitives/angular#6]
![image](https://github.com/BasicPrimitives/angular/assets/40539126/db9c9193-2e38-4758-899b-49e24ad628e1)

**Comment by dabasejumper** [comment]
I was just trying to do this as well. Looks like an awesome package to try and play around with. No Bueno with Angular 17 though.

**Comment by rabdo-alter-ego** [comment]
hi, maybe we are late to the party, but we really need support for angular > 18. Are you going to release something to solve incompatibility issues with the newer versions of angular?

**Comment by BasicPrimitives** [comment]
Published version 6,5,3 for Angular 18 support
